version: '3.8'
name: '4it573-dreamify'

services:
  mongodb:
    image: mongo:7.0.9
    container_name: mongo
    volumes:
      - db:/data/db
    ports:
      - '27017:27017'
    env_file:
      - db.env
    networks:
      - network

  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - app.env
    links:
      - mongodb
    networks:
      - network

volumes:
  db:
    driver: local

networks:
  network:
    driver: bridge
